const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {FocusTimer,freshState}=require('../dist/core/timer');
const {StateStore,validState}=require('../dist/core/store');
const {plantAt,validCultivation}=require('../dist/shared/garden');
function setup(state){let now=100000;const timer=new FocusTimer(state,()=>now);return{timer,advance(ms){now+=ms},now:()=>now};}
function grow(c,seed){c.timer.dispatch({type:'seed',seed});c.timer.dispatch({type:'start',minutes:1,label:''});c.advance(60000);c.timer.tick();}
test('old progress migrates without changing flower count, appearance or positions',()=>{const old=freshState();old.totalSessions=25;const c=setup(old);assert.equal(c.timer.state.totalSessions,25);for(let i=0;i<25;i++){assert.equal(plantAt(25,c.timer.state.cultivation,i),i);assert.equal(c.timer.state.cultivation.species[i],undefined);}assert.equal(validState(c.timer.checkpoint()),true);});
test('each seed produces its own permanent flower exactly once',()=>{const c=setup();for(const seed of ['daisy','sunflower','lavender'])grow(c,seed);assert.deepEqual(c.timer.state.cultivation.species,{'0':'daisy','1':'sunflower','2':'lavender'});c.timer.tick();assert.equal(c.timer.state.totalSessions,3);});
test('seed locks for running and paused sessions and survives a reopen',()=>{const c=setup();c.timer.dispatch({type:'seed',seed:'lavender'});c.timer.dispatch({type:'start',minutes:1,label:''});assert.throws(()=>c.timer.dispatch({type:'seed',seed:'sunflower'}));c.advance(30000);c.timer.pause();assert.throws(()=>c.timer.dispatch({type:'seed',seed:'daisy'}));const restored=new FocusTimer(c.timer.checkpoint(),c.now);assert.equal(restored.state.cultivation.activeSeed,'lavender');restored.dispatch({type:'resume'});c.advance(30000);restored.tick();assert.equal(restored.state.cultivation.species[0],'lavender');});
test('moving, swapping and next completion never lose or duplicate plants',()=>{const c=setup();grow(c,'daisy');grow(c,'sunflower');const move=(id,to)=>c.timer.dispatch({type:'movePlant',plant:id,to});move(0,11);assert.equal(plantAt(2,c.timer.state.cultivation,0),null);move(1,11);assert.equal(plantAt(2,c.timer.state.cultivation,1),0);assert.equal(plantAt(2,c.timer.state.cultivation,11),1);grow(c,'lavender');assert.equal(plantAt(3,c.timer.state.cultivation,0),2);assert.equal(validCultivation(c.timer.state.cultivation,3),true);assert.equal(c.timer.state.totalSessions,3);});
test('invalid moves and seed values leave the garden unchanged',()=>{const c=setup();grow(c,'daisy');const before=structuredClone(c.timer.state.cultivation);for(const [plant,to] of [[-1,0],[1,0],[0,-1],[0,12],[0,NaN],[0,1.2]])assert.throws(()=>c.timer.dispatch({type:'movePlant',plant,to}));for(const seed of ['bad','__proto__',null])assert.throws(()=>c.timer.dispatch({type:'seed',seed}));assert.deepEqual(c.timer.state.cultivation,before);});
test('demos, breaks and unfinished sessions never create a flower',()=>{const c=setup();c.timer.dispatch({type:'seed',seed:'sunflower'});c.timer.dispatch({type:'demo'});c.advance(20000);c.timer.tick();assert.equal(c.timer.state.cultivation.activeSeed,'sunflower');c.timer.dispatch({type:'rest'});c.advance(10000);c.timer.tick();c.timer.dispatch({type:'start',minutes:1,label:''});c.timer.dispatch({type:'end'});assert.deepEqual(c.timer.state.cultivation.species,{});assert.equal(c.timer.state.totalSessions,0);});
test('flower choices and rearrangement survive disk save/load',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'moss-seeds-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const store=new StateStore(path.join(dir,'progress.json'));const c=setup();grow(c,'sunflower');c.timer.dispatch({type:'movePlant',plant:0,to:9});store.save(c.timer.checkpoint());const restored=new FocusTimer(store.load());assert.deepEqual(restored.state.cultivation,c.timer.state.cultivation);assert.equal(plantAt(1,restored.state.cultivation,9),0);});
test('saved gardens reject collisions and unknown species',()=>{const c=setup();grow(c,'daisy');grow(c,'lavender');let s=c.timer.checkpoint();s.cultivation.positions={'0':1};assert.equal(validState(s),false);s=c.timer.checkpoint();s.cultivation.species['0']='weed';assert.equal(validState(s),false);});
